[3024_day]
background = '#282828'
foreground = '#3A3332'
color1 = '#00A0E4'
color2 = '#B5E4F4'
color3 = '#DA2C20'
color4 = '#FCEC02'
color5 = '#D6D4D3'
color6 = '#00A152'

[alien_blood]
background = '#0F160F'
foreground = '#637D75'
color1 = '#73F990'
color2 = '#2F7E25'
color3 = '#7F2B26'
color4 = '#0058DF'
color5 = '#647D75'
color6 = '#73F990'

[alucard]
background = '#222330'
foreground = '#CEF3FF'
color1 = '#FA0074'
color2 = '#FF5454'
color3 = '#3282FF'
color4 = '#FF78C5'
color5 = '#FF5454'
color6 = '#F0FA8B'

[arc_dark_crimson]
background = '#292D3E'
foreground = '#F9F9F9'
color1 = '#CC6666'
color2 = '#7C8189'
color3 = '#DC141E'
color4 = '#F0883E'
color5 = '#586875'
color6 = '#65ACFF'

[arch_linux]
background = '#222C37'
foreground = '#FFFFFF'
color1 = '#1793D1'
color2 = '#FFFFFF'
color3 = '#1793D1'
color4 = '#FFFFFF'
color5 = '#1793D1'
color6 = '#FFFFFF'

[argonaut]
background = '#0D0F18'
foreground = '#FFFAF3'
color1 = '#008DF8'
color2 = '#00D7EB'
color3 = '#FF273F'
color4 = '#8CE00A'
color5 = '#FFB900'
color6 = '#9A5FEB'

[default]
background = '#0F101A'
foreground = '#F1FFFF'
color1 = '#F1FFFF'
color2 = '#4C566A'
color3 = '#A151D3'
color4 = '#F07178'
color5 = '#FB9F7F'
color6 = '#FFD47E'

[dracula]
background = '#292D3E'
foreground = '#FFFFFF'
color1 = '#FF5454'
color2 = '#F1FFFF'
color3 = '#5AF78D'
color4 = '#BD93F9'
color5 = '#7197E7'
color6 = '#FFB86C'

[github]
background = '#24292E'
foreground = '#F1F8FF'
color1 = '#F0883E'
color2 = '#F8E3A1'
color3 = '#3FB950'
color4 = '#DA3633'
color5 = '#0366D6'
color6 = '#8957E5'

[green]
background = '#212121'
foreground = '#FFFFFF'
color1 = '#2E8447'
color2 = '#3FBC64'
color3 = '#256839'
color4 = '#37A056'
color5 = '#2E8447'
color6 = '#3FBC64'

[gruvbox]
background = '#282828'
foreground = '#3C3836'
color1 = '#EBDBB2'
color2 = '#A89984'
color3 = '#FB4934'
color4 = '#FABD2F'
color5 = '#8EC07C'
color6 = '#83A598'

[material_ocean]
background = '#0F101A'
foreground = '#F1FFFF'
color1 = '#F1FFFF'
color2 = '#4C566A'
color3 = '#A151D3'
color4 = '#F07178'
color5 = '#FB9F7F'
color6 = '#FFD47E'

[nord]
background = '#212121'
foreground = '#FFFFFF'
color1 = '#F1FFFF'
color2 = '#4C566A'
color3 = '#81A1C1'
color4 = '#88C0D0'
color5 = '#A3BE8C'
color6 = '#EBCB8B'

[one_dark]
background = '#23272E'
foreground = '#FFFFFF'
color1 = '#F1FFFF'
color2 = '#4C566A'
color3 = '#C678DD'
color4 = '#E06C75'
color5 = '#61AFEF'
color6 = '#98C379'

[palenight]
background = '#292D3E'
foreground = '#F1F1F1'
color1 = '#82AAFF'
color2 = '#959DCB'
color3 = '#C3E88D'
color4 = '#82AAFF'
color5 = '#C792EA'
color6 = '#FFCB6B'

[pico]
background = '#292D3E'
foreground = '#FFFFFF'
color1 = '#FF77A8'
color2 = '#F1FFFF'
color3 = '#FFA300'
color4 = '#FF004D'
color5 = '#29ADFF'
color6 = '#00E756'

[pop]
background = '#202020'
foreground = '#FFFFFF'
color1 = '#00AABB'
color2 = '#F1FFFF'
color3 = '#0E5A94'
color4 = '#00AABB'
color5 = '#37B349'
color6 = '#F8CA12'

[purple]
background = '#292D3E'
foreground = '#FFFFFF'
color1 = '#B455C9'
color2 = '#AF82D5'
color3 = '#9E67CB'
color4 = '#7955C9'
color5 = '#B455C9'
color6 = '#B5458B'

[rosepine]
background = '#1F1D29'
foreground = '#4C566A'
color1 = '#EABBB9'
color2 = '#F1FFFF'
color3 = '#EA6F91'
color4 = '#EABBB9'
color5 = '#F1CA93'
color6 = '#9BCED7'

[atom]
background = '#161718'
foreground = '#c4c8c5'
color1 = '#fc5ef0'
color2 = '#b9b5fc'
color3 = '#94f936'
color4 = '#f5ffa7'
color5 = '#85befd'
color6 = '#b9b5fc'

[batman]
background = '#1b1d1e'
foreground = '#6e6e6e'
color1 = '#fcee0b'
color2 = '#c5c5be'
color3 = '#fcee0b'
color4 = '#dadad5'
color5 = '#615f5e'
color6 = '#dadad5'

[espresso]
background = '#323232'
foreground = '#ffffff'
color1 = '#d096d9'
color2 = '#bdd6ff'
color3 = '#e1e48a'
color4 = '#dbf4ff'
color5 = '#a4c161'
color6 = '#c1df74'

[galaxy]
background = '#1c2836'
foreground = '#545454'
color1 = '#e75598'
color2 = '#fa8b8e'
color3 = '#20af89'
color4 = '#1e9ee6'
color5 = '#ffff55'
color6 = '#589cf5'

[molokay]
background = '#121212'
foreground = '#545454'
color1 = '#fa2573'
color2 = '#f5669c'
color3 = '#0f7fcf'
color4 = '#fef26c'
color5 = '#b0e05e'
color6 = '#42a7cf'

[monalisa]
background = '#110b0d'
foreground = '#f6d56a'
color1 = '#ff4230'
color2 = '#ff5b6a'
color3 = '#ff9565'
color4 = '#f6d75c'
color5 = '#588056'
color6 = '#9eb2b3'

[neutron]
background = '#1b1d22'
foreground = '#e6e8ee'
color1 = '#3f93a8'
color2 = '#6a7b92'
color3 = '#b53f36'
color4 = '#5ab977'
color5 = '#3f93a8'
color6 = '#e6e8ee'

[nova]
background = '#3c4c54'
foreground = '#8798a3'
color1 = '#7fc1ca'
color2 = '#8799a4'
color3 = '#69c8ff'
color4 = '#d460da'
color5 = '#e5e77f'
color6 = '#00e59f'

[spacegray]
background = '#20232c'
foreground = '#b2b8c2'
color1 = '#84a6a4'
color2 = '#7c8fa3'
color3 = '#af4b57'
color4 = '#87b279'
color5 = '#e5c078'
color6 = '#b2b8c2'

[spiderman]
background = '#1b1d1e'
foreground = '#e2e2e2'
color1 = '#2b3fff'
color2 = '#737bff'
color3 = '#ff0325'
color4 = '#e22828'
color5 = '#e24655'
color6 = '#fffef6'

[the_hulk]
background = '#1b1d1e'
foreground = '#b4b4b4'
color1 = '#48ff76'
color2 = '#15b61a'
color3 = '#3afe15'
color4 = '#259d1a'
color5 = '#72579d'
color6 = '#e5e5e0'

[tokyo_night]
background = '#1a1b26'
foreground = '#a9b1d6'
color1 = '#c0caf5'
color2 = '#3d59a1'
color3 = '#e0af68'
color4 = '#f7768e'
color5 = '#73daca'
color6 = '#bb9af7'

[wombat]
background = '#453a39'
foreground = '#ded9ce'
color1 = '#5da9f6'
color2 = '#f58b7f'
color3 = '#dcf88f'
color4 = '#e86aff'
color5 = '#a5c7ff'
color6 = '#ddaaff'

[afterglow]
background = '#202020'
foreground = '#f5f5f5'
color1 = '#7dd5cf'
color2 = '#6c99ba'
color3 = '#bc5653'
color4 = '#7e8d50'
color5 = '#e5b566'
color6 = '#6c99ba'

[city_lights]
background = '#171d23'
foreground = '#ffffff'
color1 = '#b7c5d3'
color2 = '#333f4a'
color3 = '#8bd49c'
color4 = '#539afc'
color5 = '#b62d65'
color6 = '#70e1e8'

[cyberpunk_neon]
background = '#000b1e'
foreground = '#0abdc6'
color1 = '#0abdc6'
color2 = '#123e7c'
color3 = '#ff0000'
color4 = '#00ff00'
color5 = '#0abdc6'
color6 = '#d7d7d5'

[doom_one]
background = '#282c34'
foreground = '#bbc2cf'
color1 = '#51afef'
color2 = '#46d9ff'
color3 = '#98be65'
color4 = '#ecbe7b'
color5 = '#ff6c6b'
color6 = '#51afef'

[horizontal_dark]
background = '#1c1e26'
foreground = '#e0e0e0'
color1 = '#59e1e3'
color2 = '#3fc4de'
color3 = '#29d398'
color4 = '#fab795'
color5 = '#26bbd9'
color6 = '#ee64ac'

[iterm]
background = '#101421'
foreground = '#fffbf6'
color1 = '#49a4f8'
color2 = '#565656'
color3 = '#a47de9'
color4 = '#ec5357'
color5 = '#c0e17d'
color6 = '#f9da6a'

[monokay_pro]
background = '#2D2A2E'
foreground = '#fff1f3'
color1 = '#f9cc6c'
color2 = '#f38d70'
color3 = '#adda78'
color4 = '#fd6883'
color5 = '#fff1f3'
color6 = '#a8a9eb'

[moonlight]
background = '#1e2030'
foreground = '#7f85a3'
color1 = '#ff5370'
color2 = '#fc7b7b'
color3 = '#ffc777'
color4 = '#3e68d7'
color5 = '#ff5370'
color6 = '#4fd6be'

[omni]
background = '#191622'
foreground = '#f8f8f2'
color1 = '#ff79c6'
color2 = '#8d79ba'
color3 = '#bb006b'
color4 = '#aa91e3'
color5 = '#530aba'
color6 = '#effa78'

[pencil]
background = '#212121'
foreground = '#f1f1f1'
color1 = '#fb007a'
color2 = '#f1f1f1'
color3 = '#5fd7af'
color4 = '#f3e430'
color5 = '#20bbfc'
color6 = '#6855de'

[tender]
background = '#282828'
foreground = '#eeeeee'
color1 = '#ffc24b'
color2 = '#d3b987'
color3 = '#f43753'
color4 = '#c9d05c'
color5 = '#ffc24b'
color6 = '#73cef4'

[lovelace]
background = '#1D1F28'
foreground = '#FDFDFD'
color1 = '#FF4971'
color2 = '#F37F97'
color3 = '#F2A272'
color4 = '#8897F4'
color5 = '#C574DD'
color6 = '#79E6F3'

[tokyo_night_storm]
background = '#24283b'
foreground = '#a9b1d6'
color1 = '#7da6ff'
color2 = '#bb9af7'
color3 = '#9ece6a'
color4 = '#ff9e64'
color5 = '#7aa2f7'
color6 = '#f7768e'

[ubuntu]
background = '#300a24'
foreground = '#eeeeec'
color1 = '#ef2929'
color2 = '#fce94f'
color3 = '#729fcf'
color4 = '#ad7fa8'
color5 = '#34e2e2'
color6 = '#eeeeec'

[ayu_dark]
background = '#0A0E14'
foreground = '#B3B1AD'
color1 = '#F9AF4F'
inact3ve = '#FAE994'
color4 = '#EA6C73'
color5 = '#91B362'
color2 = '#59C2FF'
color6 = '#95E6CB'

[base_16]
background = '#181818'
foreground = '#d8d8d8'
color1 = '#f7ca88'
color2 = '#ab4642'
color3 = '#f8f8f8'
color4 = '#ba8baf'
color5 = '#86c1b9'
color6 = '#ab4642'

[breeze]
background = '#eff0f1'
foreground = '#31363b'
color1 = '#1cdc9a'
color2 = '#16a085'
color3 = '#31363b'
color4 = '#1b668f'
color5 = '#11d116'
color6 = '#9b59b6'

[challenger_deep]
background = '#1e1c31'
foreground = '#cbe1e7'
color1 = '#ff271d'
color2 = '#ff5458'
color3 = '#ffb378'
color4 = '#62d196'
color5 = '#65b2ff'
color6 = '#906cff'

[cobalt2]
background = '#122637'
foreground = '#f0cb09'
color1 = '#fee409'
color2 = '#bbbbbb'
color3 = '#5555ff'
color4 = '#ff55ff'
color5 = '#6ae3f9'
color6 = '#ffffff'

[gotham]
background = '#0a0f14'
foreground = '#98d1ce'
color1 = '#195465'
color2 = '#4e5165'
color3 = '#d26939'
color4 = '#081f2d'
color5 = '#245361'
color6 = '#d3ebe9'
