[3024_day]
background = '#282828'
foreground = '#3A3332'
color1     = '#00A0E4'
color2     = '#B5E4F4'
color3     = '#DA2C20'
color4     = '#FCEC02'
color5     = '#D6D4D3'
color6     = '#00A152'

[alien_blood]
background = '#0F160F'
foreground = '#637D75'
color1     = '#73F990'
color2     = '#2F7E25'
color3     = '#7F2B26'
color4     = '#0058DF'
color5     = '#647D75'
color6     = '#73F990'

[alucard]
background = '#222330'
foreground = '#CEF3FF'
color1     = '#FA0074'
color2     = '#FF5454'
color3     = '#3282FF'
color4     = '#FF78C5'
color5     = '#FF5454'
color6     = '#F0FA8B'

[arc_dark_crimson]
background = '#292D3E'
foreground = '#F9F9F9'
color1     = '#CC6666'
color2     = '#7C8189'
color3     = '#DC141E'
color4     = '#F0883E'
color5     = '#586875'
color6     = '#65ACFF'

[arch_linux]
background = '#222C37'
foreground = '#FFFFFF'
color1     = '#1793D1'
color2     = '#FFFFFF'
color3     = '#1793D1'
color4     = '#FFFFFF'
color5     = '#1793D1'
color6     = '#FFFFFF'

[argonaut]
background = '#0D0F18'
foreground = '#FFFAF3'
color1     = '#008DF8'
color2     = '#00D7EB'
color3     = '#FF273F'
color4     = '#8CE00A'
color5     = '#FFB900'
color6     = '#9A5FEB'

[default]
background = '#0F101A'
foreground = '#F1FFFF'
color1     = '#F1FFFF'
color2     = '#4C566A'
color3     = '#A151D3'
color4     = '#F07178'
color5     = '#FB9F7F'
color6     = '#FFD47E'

[dracula]
background = '#292D3E'
foreground = '#FFFFFF'
color1     = '#FF5454'
color2     = '#F1FFFF'
color3     = '#5AF78D'
color4     = '#BD93F9'
color5     = '#7197E7'
color6     = '#FFB86C'

[nord]
background = '#212121'
foreground = '#FFFFFF'
color1     = '#F1FFFF'
color2     = '#4C566A'
color3     = '#81A1C1'
color4     = '#88C0D0'
color5     = '#A3BE8C'
color6     = '#EBCB8B'

[one_dark]
background = '#23272E'
foreground = '#FFFFFF'
color1     = '#F1FFFF'
color2     = '#4C566A'
color3     = '#C678DD'
color4     = '#E06C75'
color5     = '#61AFEF'
color6     = '#98C379'

[palenight]
background = '#292D3E'
foreground = '#F1F1F1'
color1     = '#82AAFF'
color2     = '#959DCB'
color3     = '#C3E88D'
color4     = '#82AAFF'
color5     = '#C792EA'
color6     = '#FFCB6B'

[pico]
background = '#292D3E'
foreground = '#FFFFFF'
color1     = '#FF77A8'
color2     = '#F1FFFF'
color3     = '#FFA300'
color4     = '#FF004D'
color5     = '#29ADFF'
color6     = '#00E756'

[pop]
background = '#202020'
foreground = '#FFFFFF'
color1     = '#00AABB'
color2     = '#F1FFFF'
color3     = '#0E5A94'
color4     = '#00AABB'
color5     = '#37B349'
color6     = '#F8CA12'

[purple]
color4     = '#7955C9'
color5     = '#B455C9'
color6     = '#B5458B'
background = '#1b1b23'
foreground = '#86799a'
color1     = '#bfa3ff'
color2     = '#554d9a'
color3     = '#ff6387'

[rosepine]
background = '#1F1D29'
foreground = '#4C566A'
color1     = '#EABBB9'
color2     = '#F1FFFF'
color3     = '#EA6F91'
color4     = '#EABBB9'
color5     = '#F1CA93'
color6     = '#9BCED7'

[atom]
background = '#161718'
foreground = '#c4c8c5'
color1     = '#fc5ef0'
color2     = '#b9b5fc'
color3     = '#94f936'
color4     = '#f5ffa7'
color5     = '#85befd'
color6     = '#b9b5fc'

[batman]
background = '#1b1d1e'
foreground = '#6e6e6e'
color1     = '#fcee0b'
color2     = '#c5c5be'
color3     = '#fcee0b'
color4     = '#dadad5'
color5     = '#615f5e'
color6     = '#dadad5'

[espresso]
background = '#323232'
foreground = '#ffffff'
color1     = '#d096d9'
color2     = '#bdd6ff'
color3     = '#e1e48a'
color4     = '#dbf4ff'
color5     = '#a4c161'
color6     = '#c1df74'

[galaxy]
background = '#1c2836'
foreground = '#545454'
color1     = '#e75598'
color2     = '#fa8b8e'
color3     = '#20af89'
color4     = '#1e9ee6'
color5     = '#ffff55'
color6     = '#589cf5'

[monalisa]
background = '#110b0d'
foreground = '#f6d56a'
color1     = '#ff4230'
color2     = '#ff5b6a'
color3     = '#ff9565'
color4     = '#f6d75c'
color5     = '#588056'
color6     = '#9eb2b3'

[neutron]
background = '#1b1d22'
foreground = '#e6e8ee'
color1     = '#3f93a8'
color2     = '#6a7b92'
color3     = '#b53f36'
color4     = '#5ab977'
color5     = '#3f93a8'
color6     = '#e6e8ee'

[nova]
background = '#3c4c54'
foreground = '#8798a3'
color1     = '#7fc1ca'
color2     = '#8799a4'
color3     = '#69c8ff'
color4     = '#d460da'
color5     = '#e5e77f'
color6     = '#00e59f'

[spacegray]
background = '#20232c'
foreground = '#b2b8c2'
color1     = '#84a6a4'
color2     = '#7c8fa3'
color3     = '#af4b57'
color4     = '#87b279'
color5     = '#e5c078'
color6     = '#b2b8c2'

[spiderman]
background = '#1b1d1e'
foreground = '#e2e2e2'
color1     = '#2b3fff'
color2     = '#737bff'
color3     = '#ff0325'
color4     = '#e22828'
color5     = '#e24655'
color6     = '#fffef6'

[the_hulk]
background = '#1b1d1e'
foreground = '#b4b4b4'
color1     = '#48ff76'
color2     = '#15b61a'
color3     = '#3afe15'
color4     = '#259d1a'
color5     = '#72579d'
color6     = '#e5e5e0'

[tokyo_night]
background = '#1a1b26'
foreground = '#a9b1d6'
color1     = '#c0caf5'
color2     = '#3d59a1'
color3     = '#e0af68'
color4     = '#f7768e'
color5     = '#73daca'
color6     = '#bb9af7'

[wombat]
background = '#453a39'
foreground = '#ded9ce'
color1     = '#5da9f6'
color2     = '#f58b7f'
color3     = '#dcf88f'
color4     = '#e86aff'
color5     = '#a5c7ff'
color6     = '#ddaaff'

[afterglow]
background = '#202020'
foreground = '#f5f5f5'
color1     = '#7dd5cf'
color2     = '#6c99ba'
color3     = '#bc5653'
color4     = '#7e8d50'
color5     = '#e5b566'
color6     = '#6c99ba'

[city_lights]
background = '#171d23'
foreground = '#ffffff'
color1     = '#b7c5d3'
color2     = '#333f4a'
color3     = '#8bd49c'
color4     = '#539afc'
color5     = '#b62d65'
color6     = '#70e1e8'

[cyberpunk_neon]
background = '#000b1e'
foreground = '#0abdc6'
color1     = '#0abdc6'
color2     = '#123e7c'
color3     = '#ff0000'
color4     = '#00ff00'
color5     = '#0abdc6'
color6     = '#d7d7d5'

[doom_one]
background = '#282c34'
foreground = '#bbc2cf'
color1     = '#51afef'
color2     = '#46d9ff'
color3     = '#98be65'
color4     = '#ecbe7b'
color5     = '#ff6c6b'
color6     = '#51afef'

[horizontal_dark]
background = '#1c1e26'
foreground = '#e0e0e0'
color1     = '#59e1e3'
color2     = '#3fc4de'
color3     = '#29d398'
color4     = '#fab795'
color5     = '#26bbd9'
color6     = '#ee64ac'

[iterm]
background = '#101421'
foreground = '#fffbf6'
color1     = '#49a4f8'
color2     = '#565656'
color3     = '#a47de9'
color4     = '#ec5357'
color5     = '#c0e17d'
color6     = '#f9da6a'

[monokay_pro]
background = '#2D2A2E'
foreground = '#fff1f3'
color1     = '#f9cc6c'
color2     = '#f38d70'
color3     = '#adda78'
color4     = '#fd6883'
color5     = '#fff1f3'
color6     = '#a8a9eb'

[moonlight]
background = '#1e2030'
foreground = '#7f85a3'
color1     = '#ff5370'
color2     = '#fc7b7b'
color3     = '#ffc777'
color4     = '#3e68d7'
color5     = '#ff5370'
color6     = '#4fd6be'

[tender]
background = '#282828'
foreground = '#eeeeee'
color1     = '#ffc24b'
color2     = '#d3b987'
color3     = '#f43753'
color4     = '#c9d05c'
color5     = '#ffc24b'
color6     = '#73cef4'

[lovelace]
background = '#1D1F28'
foreground = '#FDFDFD'
color1     = '#FF4971'
color2     = '#F37F97'
color3     = '#F2A272'
color4     = '#8897F4'
color5     = '#C574DD'
color6     = '#79E6F3'

[tokyo_night_storm]
background = '#24283b'
foreground = '#a9b1d6'
color1     = '#7da6ff'
color2     = '#bb9af7'
color3     = '#9ece6a'
color4     = '#ff9e64'
color5     = '#7aa2f7'
color6     = '#f7768e'

[ubuntu]
background = '#300a24'
foreground = '#eeeeec'
color1     = '#ef2929'
color2     = '#fce94f'
color3     = '#729fcf'
color4     = '#ad7fa8'
color5     = '#34e2e2'
color6     = '#eeeeec'

[ayu_dark]
background = '#0A0E14'
foreground = '#B3B1AD'
color1     = '#F9AF4F'
color2     = '#59C2FF'
color3     = '#FAE994'
color4     = '#EA6C73'
color5     = '#91B362'
color6     = '#95E6CB'

[base_16]
background = '#181818'
foreground = '#d8d8d8'
color1     = '#f7ca88'
color2     = '#ab4642'
color3     = '#f8f8f8'
color4     = '#ba8baf'
color5     = '#86c1b9'
color6     = '#ab4642'

[breeze]
background = '#eff0f1'
foreground = '#31363b'
color1     = '#1cdc9a'
color2     = '#16a085'
color3     = '#31363b'
color4     = '#1b668f'
color5     = '#11d116'
color6     = '#9b59b6'

[challenger_deep]
background = '#1e1c31'
foreground = '#cbe1e7'
color1     = '#ff271d'
color2     = '#ff5458'
color3     = '#ffb378'
color4     = '#62d196'
color5     = '#65b2ff'
color6     = '#906cff'

[cobalt2]
background = '#122637'
foreground = '#f0cb09'
color1     = '#fee409'
color2     = '#bbbbbb'
color3     = '#5555ff'
color4     = '#ff55ff'
color5     = '#6ae3f9'
color6     = '#ffffff'

[gotham]
background = '#0a0f14'
foreground = '#98d1ce'
color1     = '#195465'
color2     = '#4e5165'
color3     = '#d26939'
color4     = '#081f2d'
color5     = '#245361'
color6     = '#d3ebe9'

[3024_night]
background = '#090200'
foreground = '#a4a1a1'
color1     = '#7f7c7b'
color2     = '#3a3332'
color3     = '#ccab53'
color4     = '#00a0e4'
color5     = '#a06994'
color6     = '#b5e4f4'

[adventuretime]
background = '#050404'
foreground = '#f8dbc0'
color1     = '#1896c6'
color2     = '#4e7bbf'
color5     = '#9dff6e'
color4     = '#efc11a'
color3     = '#e6741d'
color6     = '#6fa497'

[apprentice]
background = '#323232'
foreground = '#c8c8c8'
color1     = '#be7472'
color2     = '#709772'
color3     = '#989772'
color4     = '#7199bc'
color5     = '#727399'
color6     = '#719899'

[arthur]
background = '#1c1c1c'
foreground = '#ddeedd'
color1     = '#cd5c5c'
color2     = '#86af80'
color3     = '#e8ae5b'
color4     = '#6495ed'
color5     = '#deb887'
color6     = '#b0c4de'

[ateliersulphurpool]
background = '#5e6686'
foreground = '#f4f7ff'
color1     = '#6678cc'
color2     = '#283256'
color3     = '#c08a2f'
color4     = '#3d8ed0'
color5     = '#c76a28'
color6     = '#21a1c8'

[ayu_light]
background = '#fafafa'
foreground = '#5b6673'
color1     = '#ff3333'
color2     = '#ffa3aa'
color3     = '#73d7ff'
color4     = '#7ff0cb'
color5     = '#4cbe99'
color6     = '#b8e532'

[ayu_mirage]
background = '#212733'
foreground = '#d9d7ce'
color1     = '#d4bfff'
color2     = '#73d0ff'
color3     = '#fad07b'
color4     = '#6dcbfa'
color5     = '#cfbafa'
color6     = '#90e1c6'

[belafonte_day]
background = '#d4ccb9'
foreground = '#45363b'
color1     = '#858062'
color2     = '#e9a448'
color3     = '#958b83'
color4     = '#416978'
color5     = '#96522b'
color6     = '#98999c'

[belafonte_night]
background = '#20111a'
foreground = '#958b83'
color1     = '#bd100d'
color2     = '#858062'
color3     = '#e9a448'
color4     = '#416978'
color5     = '#96522b'
color6     = '#98999c'

[birdsofparadise]
background = '#2a1e1d'
foreground = '#dfdab7'
color1     = '#be2d26'
color2     = '#6ba08a'
color3     = '#e99c29'
color4     = '#5a86ac'
color5     = '#ab80a6'
color6     = '#74a5ac'

[blazer]
background = '#0d1925'
foreground = '#d9e5f1'
color1     = '#b87979'
color2     = '#79b879'
color3     = '#b8b879'
color4     = '#7979b8'
color5     = '#b879b8'
color6     = '#79b8b8'

[borland]
foreground = '#ffff4d'
background = '#4e4e4e'
color1     = '#ceffab'
color2     = '#b5dcfe'
color3     = '#ff9cfe'
color4     = '#dfdffe'
color5     = '#ffffff'
color6     = '#c6c4fd'

[bright_lights]
background = '#191919'
foreground = '#b2c8d6'
color1     = '#ff355b'
color2     = '#b6e875'
color3     = '#ffc150'
color4     = '#75d3ff'
color5     = '#b975e6'
color6     = '#6cbeb5'

[brogrammer]
background = '#131313'
foreground = '#d6dae4'
color1     = '#f71118'
color2     = '#1dd260'
color3     = '#f2bd09'
color4     = '#2a84d2'
color5     = '#4e59b7'
color6     = '#0f80d5'

[chalk]
background = '#2b2c2e'
foreground = '#d2d8d9'
color1     = '#b23a51'
color2     = '#789a69'
color3     = '#b9ab4a'
color4     = '#2a7fac'
color5     = '#bc4f5a'
color6     = '#44a799'

[chalkboard]
background = '#29262f'
foreground = '#d9e6f2'
color1     = '#c37372'
color2     = '#72c373'
color3     = '#c2c372'
color4     = '#7372c3'
color5     = '#c372c2'
color6     = '#72c2c3'

[ciapre]
background = '#181c27'
foreground = '#ada37a'
color1     = '#2f97c6'
color2     = '#566d8c'
color3     = '#d33060'
color4     = '#cc8a3e'
color5     = '#724c7c'
color6     = '#5b4f4a'


[cobalt_neon]
background = '#142838'
foreground = '#8ff586'
color1     = '#ba45b1'
color2     = '#3aa5ff'
color3     = '#fff688'
color4     = '#6cbc67'
color5     = '#8ff586'
color6     = '#781aa0'

[crayonponyfish]
background = '#140607'
foreground = '#685259'
color1     = '#90002a'
color2     = '#579523'
color3     = '#aa301b'
color4     = '#8b87af'
color5     = '#682e50'
color6     = '#e8a766'

[dark_pastel]
background = '#000000'
foreground = '#ffffff'
color1     = '#ff5555'
color2     = '#55ff55'
color3     = '#ffff55'
color4     = '#5555ff'
color5     = '#ff55ff'
color6     = '#55ffff'

[darkside]
background = '#212324'
foreground = '#b9b9b9'
color1     = '#8e69c8'
color2     = '#1c98e8'
color3     = '#e8331c'
color4     = '#68c156'
color5     = '#f1d32b'
color6     = '#1c98e8'

[desert]
background = '#333333'
foreground = '#ffffff'
color1     = '#ffff55'
color2     = '#f0e68c'
color3     = '#ffa0a0'
color4     = '#cd853f'
color5     = '#ffdead'
color6     = '#f5deb3'

[duotone_dark]
background = '#1f1c27'
foreground = '#b6a0ff'
color1     = '#d8393d'
color2     = '#2dcc72'
color3     = '#d8b76e'
color4     = '#ffc183'
color5     = '#dd8d40'
color6     = '#2388ff'

[earthsong]
background = '#282420'
foreground = '#e5c6a8'
color1     = '#f4ae2e'
color2     = '#c84134'
color3     = '#84c44b'
color4     = '#1397b9'
color5     = '#d0623c'
color6     = '#4f9452'

[espresso_libre]
background = '#2a211c'
foreground = '#b8a898'
color1     = '#43a8ed'
color2     = '#05989a'
color3     = '#fffa5c'
color4     = '#34e2e2'
color5     = '#ededec'
color6     = '#ff8089'

[fideloper]
background = '#282f32'
foreground = '#dad9df'
color1     = '#d35f5a'
color2     = '#a86571'
color3     = '#7c84c4'
color4     = '#5b5db2'
color5     = '#81908f'
color6     = '#309185'


[frontenddelight]
background = '#1b1b1d'
foreground = '#acacac'
color1     = '#fcc224'
color2     = '#565746'
color3     = '#f9761d'
color4     = '#2c70b7'
color5     = '#f02d4e'
color6     = '#3ba0a5'

[glacier]
background = '#a0b6d3'
foreground = '#ffffff'
color1     = '#1f5872'
color2     = '#2a8bc1'
color3     = '#404a55'
color4     = '#ea4727'
color5     = '#bd2523'
color6     = '#778397'

[grape]
background = '#161423'
foreground = '#9e9ea0'
color1     = '#ec2160'
color2     = '#a9bbeb'
color3     = '#ac81c1'
color4     = '#487cf4'
color5     = '#8c35c8'
color6     = '#f0719a'

[gruvbox_dark]
background = '#282828'
foreground = '#ebdbb2'
color1     = '#fabd2d'
color2     = '#83a598'
color3     = '#fb4934'
color4     = '#8ec07c'
color5     = '#928374'
color6     = '#928374'

[hardcore]
background = '#121212'
foreground = '#a0a0a0'
color1     = '#f92672'
color2     = '#a6e22e'
color3     = '#fd971f'
color4     = '#66d9ef'
color5     = '#9e6ffe'
color6     = '#5e7175'

[harper]
background = '#000000'
foreground = '#a7a39c'
color1     = '#f7b63e'
color2     = '#7fb5e1'
color3     = '#d6da24'
color4     = '#489d48'
color5     = '#b295c5'
color6     = '#f4bed6'

[hurtado]
background = '#000000'
foreground = '#dadbda'
color1     = '#fbe74a'
color2     = '#a5df55'
color3     = '#dbdbdb'
color4     = '#486387'
color5     = '#fc5ef0'
color6     = '#85e9fe'

[hybrid]
background = '#161718'
foreground = '#b7bcb9'
color1     = '#b74d50'
color2     = '#b3be5a'
color3     = '#e3b55e'
color4     = '#6d90b0'
color5     = '#a07eab'
color6     = '#7fbeb3'

[japanesque]
background = '#1d1d1d'
foreground = '#f7f6ec'
color1     = '#ce3e60'
color2     = '#135879'
color3     = '#5f4190'
color4     = '#4c99d3'
color5     = '#a57fc4'
color6     = '#389aac'

[later_this_evening]
background = '#212121'
foreground = '#949494'
color1     = '#d35a5f'
color2     = '#afba66'
color3     = '#e5d289'
color4     = '#a0b9d5'
color5     = '#bf92d5'
color6     = '#91beb6'

[lavandula]
background = '#050014'
foreground = '#736d7c'
color1     = '#7c1525'
color2     = '#337e6f'
color3     = '#7f6f49'
color4     = '#4f4a7f'
color5     = '#593f7e'
color6     = '#57767f'

[liquidcarbon]
background = '#2f2f2f'
foreground = '#afc2c2'
color1     = '#bccccc'
color2     = '#549a6f'
color3     = '#ccac00'
color4     = '#0099cc'
color5     = '#cc68c8'
color6     = '#79c4cc'

[molokai]
background = '#121212'
foreground = '#bbbbbb'
color1     = '#fa2573'
color2     = '#97e123'
color3     = '#dfd460'
color4     = '#0f7fcf'
color5     = '#8700ff'
color6     = '#42a7cf'

[monokai_pro_filter_octagon]
background = '#3a3d4b'
foreground = '#eaf2f1'
color1     = '#ff657a'
color2     = '#bad761'
color3     = '#ffd76d'
color4     = '#ff9b5e'
color5     = '#c39ac9'
color6     = '#9cd1bb'

[monokai_pro_filter_ristretto]
background = '#403838'
foreground = '#fff1f3'
color1     = '#fd6883'
color2     = '#adda78'
color3     = '#f9cc6c'
color4     = '#f38d70'
color5     = '#a8a9eb'
color6     = '#85dacc'

[monokai_pro_filter_spectrum]
background = '#363537'
foreground = '#f7f1ff'
color1     = '#fc618d'
color2     = '#7bd88f'
color3     = '#fce566'
color4     = '#fd9353'
color5     = '#948ae3'
color6     = '#5ad4e6'

[n0tch2k]
background = '#222222'
foreground = '#a0a0a0'
color1     = '#a95551'
color2     = '#666666'
color3     = '#a98051'
color4     = '#657d3e'
color5     = '#767676'
color6     = '#c9c9c9'

[pencil_dark]
background = '#202020'
foreground = '#f0f0f0'
color1     = '#c30670'
color2     = '#10a778'
color3     = '#f3e42f'
color4     = '#008ec4'
color5     = '#523b78'
color6     = '#20a4b9'

[pencil_light]
background = '#f0f0f0'
foreground = '#414141'
color1     = '#6854de'
color2     = '#20bafb'
color3     = '#c30670'
color4     = '#4fb8cc'
color5     = '#fb0079'
color6     = '#20a4b9'

[relaxed_afterglow]
background = '#353a44'
foreground = '#d9d9d9'
color1     = '#bc5653'
color2     = '#909d63'
color3     = '#ebc17a'
color4     = '#6a8799'
color5     = '#b06698'
color6     = '#c9dfff'

[rippedcasts]
background = '#2b2b2b'
foreground = '#ffffff'
color1     = '#ccae95'
color2     = '#a7ff60'
color3     = '#beba1f'
color4     = '#74a4af'
color5     = '#ff73fd'
color6     = '#5a637e'

[royal]
background = '#100814'
foreground = '#504868'
color1     = '#d4346c'
color2     = '#8fb9f9'
color3     = '#a479e2'
color4     = '#abd3eb'
color5     = '#9d8bbd'
color6     = '#8aaabd'

[seashells]
background = '#08131a'
foreground = '#deb88d'
color1     = '#fdd29e'
color2     = '#027b9b'
color3     = '#d38677'
color4     = '#1d4850'
color5     = '#68d3f0'
color6     = '#50a3b5'

[snazzy]
background = '#282a36'
foreground = '#eff0eb'
color1     = '#ff5c57'
color2     = '#5af78e'
color3     = '#f3f99d'
color4     = '#57c7ff'
color5     = '#ff6ac1'
color6     = '#9aedfe'

[source_code_x]
background = '#1f1f24'
foreground = '#000000'
color1     = '#fb695d'
color2     = '#74b391'
color3     = '#fc8e3e'
color4     = '#9586f4'
color5     = '#fb5ea3'
color6     = '#79c8b6'

[wryan]
background = '#101010'
foreground = '#999993'
color1     = '#8c4665'
color2     = '#287373'
color3     = '#7c7c99'
color4     = '#395573'
color5     = '#5e468c'
color6     = '#31658c'
