#!/bin/sh
# Generated on 2023-07-23 20:59
Print
	scrot 'screenshot_%Y%m%d_%H%M%S.jpg' -e 'mv $f $$(xdg-user-dir SCREENSHOTS)'
{ XF86AudioLowerVolume,XF86AudioRaiseVolume }
	amixer set Master {5%-,5%+}
XF86AudioMute
	amixer -D pulse set Master 1+ toggle
{ XF86AudioNext,XF86AudioPlay,XF86AudioPrev,XF86AudioStop }
	playerctl {next,play-pause,previous,stop}
{ XF86MonBrightnessDown,XF86MonBrightnessUp }
	xbacklight {-dec,-inc} 5
alt Escape
	xfce4-taskmanager
alt Print
	xfce4-screenshooter
alt {Left,Right}
	variety -{p,n}
super F1
	brave
super F2
	code
super F8
	thunar
super F9
	thunderbird
super e
	code
super f
	firefox
super KP_Enter
	gnome-calculator
super Return
	kitty
super + ctrl Return
	thunar
super + shift Escape
	xkill
super + shift o
	picom ~/.config/qtile/.config/picom-toogle.sh
super + shift s
	pkill -USR1 -x sxhkd
